In [1]:
# import numpy
import numpy as np

In [ ]:
# !pip install numpy -- required only when numpy is not instlled 

In [2]:
# create an nd array from python list

mylist = [1,2,3,4,5,6]

In [3]:
type(mylist)

list

In [4]:
# np.array() : which will convert given object into an array

my_arr = np.array(mylist)

In [5]:
my_arr

array([1, 2, 3, 4, 5, 6])

In [6]:
type(my_arr)

numpy.ndarray

In [ ]:
# just for demo , no need to attempt this code

In [7]:
import cv2  #computer vision library to deal with image and video data 

In [8]:
pic= cv2.imread('sample_img.jpeg')

In [9]:
pic

array([[[158, 138,  53],
        [159, 139,  54],
        [159, 139,  54],
        ...,
        [125,  67,  62],
        [128,  71,  62],
        [136,  79,  70]],

       [[159, 139,  54],
        [159, 139,  54],
        [160, 140,  55],
        ...,
        [114,  58,  53],
        [115,  60,  53],
        [122,  67,  60]],

       [[160, 139,  57],
        [161, 140,  58],
        [161, 140,  58],
        ...,
        [105,  50,  47],
        [103,  49,  42],
        [111,  57,  50]],

       ...,

       [[ 85,  79, 120],
        [ 84,  78, 119],
        [ 83,  77, 118],
        ...,
        [ 66,  70, 129],
        [ 68,  72, 131],
        [ 68,  72, 131]],

       [[ 98,  88, 124],
        [ 98,  88, 124],
        [ 97,  87, 123],
        ...,
        [ 65,  68, 129],
        [ 66,  69, 130],
        [ 66,  69, 130]],

       [[108,  94, 128],
        [108,  94, 128],
        [106,  92, 126],
        ...,
        [ 66,  67, 128],
        [ 66,  67, 128],
        [ 66,  67, 128]]

In [10]:
type(pic)

numpy.ndarray

In [ ]:
# RGB = 0:255

In [11]:
pic.shape

(151, 270, 3)

In [12]:
# Numpy vs Python

In [13]:
# speed , storage

In [14]:
# how much memory is consumed by single int
num=5

In [15]:
import sys

In [16]:
sys.getsizeof(num), 'bytes'

(28, 'bytes')

In [17]:
# for 1000 integers we need  : 28000 bytes

In [18]:
my_arr

array([1, 2, 3, 4, 5, 6])

In [19]:
# itemsize : return size of single element in an array

In [20]:
my_arr.itemsize, 'bytes'

(8, 'bytes')

In [ ]:
# for 1000 numbers i am saving 20000 bytes

In [21]:
my_arr.nbytes, 'bytes'

(48, 'bytes')

In [22]:
# time 

In [23]:
import time

In [24]:
time.time()

1716023263.052223

In [28]:
size = 1000000
l1 = range(size)
l2 = range(size)

ar1 = np.arange(size)
ar2 = np.arange(size)

start1 = time.time()
result1 = [x+y for x,y in zip(l1,l2)]
stop1 = time.time()

print("time taken by list is : ", (stop1-start1)*1000, 'ms')

time taken by list is :  280.43532371520996 ms


In [29]:
size = 1000000
l1 = range(size)
l2 = range(size)

ar1 = np.arange(size)
ar2 = np.arange(size)

start2 = time.time()
result2 = ar1+ar2
stop2 = time.time()

print("time taken by an array is : ", (stop2-start2)*1000, 'ms')

time taken by an array is :  5.622148513793945 ms


# Numpy

In [30]:
# creating 1D array

In [31]:
a = np.array([1,2,3,4,5,6])

In [32]:
a

array([1, 2, 3, 4, 5, 6])

In [33]:
a[3]

4

In [34]:
# creating 2D array

In [55]:
mylist = [[1,2,3],[4,5,6]]
b = np.array(mylist)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
# shape : rows , columns
b.shape

(2, 2)

In [37]:
# ndim : returns number of dimesions
a.ndim

1

In [38]:
b.ndim

2

In [40]:
np.array([[[ 1, 2, 3 ]]]).ndim

3

In [41]:
pic.ndim

3

In [ ]:
# lets create 3D array

In [42]:
mylist1 = [
    [[1,2,3],[3,4,5]],
    [[8,9,10],[3,7,5]]
]
c = np.array(mylist1)
c

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 8,  9, 10],
        [ 3,  7,  5]]])

In [43]:
c.ndim

3

In [45]:
# slicing

In [47]:
b

array([[1, 2],
       [3, 4]])

In [49]:
b[1][0]

3

In [52]:
c[1][0][2]

10

In [53]:
# how can i find 4

In [56]:
b[5,6]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
b[1,1:]

array([5, 6])

In [58]:
c

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 8,  9, 10],
        [ 3,  7,  5]]])

In [73]:
c[1]

array([[ 8,  9, 10],
       [ 3,  7,  5]])

In [74]:
c[1][0,1:]

array([ 9, 10])

In [75]:
c[1,0,1:]

array([ 9, 10])

In [ ]:
# statestical operations on data

In [76]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype = 'float')
arr1

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [77]:
print("Min value is : ", arr1.min())
print("max value is : ", arr1.max())
print("Average value is : ", arr1.mean())
print("Total value is : ", arr1.sum())

Min value is :  1.0
max value is :  12.0
Average value is :  6.5
Total value is :  78.0


In [78]:
print("column wise summation is  : ",np.sum(arr1,axis = 0))

column wise summation is  :  [15. 18. 21. 24.]


In [79]:
print("Row wise summation is  : ",np.sum(arr1,axis = 1))

Row wise summation is  :  [10. 26. 42.]


In [80]:
type(np.sum(arr1,axis = 0))

numpy.ndarray

In [81]:
print(np.sum(arr1,axis = 0))

[15. 18. 21. 24.]


In [83]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [84]:
x

array([[1, 2],
       [3, 4]])

In [85]:
y

array([[5, 6],
       [7, 8]])

In [86]:
x+y

array([[ 6,  8],
       [10, 12]])

In [87]:
x*y

array([[ 5, 12],
       [21, 32]])

In [88]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [90]:
dist  = [180,170,135,191,250]
time = [6,7,10,13,11]

d_arr = np.array(dist)
t_arr = np.array(time)

s_arr = d_arr/ t_arr
s_arr

array([30.        , 24.28571429, 13.5       , 14.69230769, 22.72727273])

In [91]:
# .add

new_arr = np.add(x,y)
new_arr

array([[ 6,  8],
       [10, 12]])

In [93]:
# multiply

new_arr1 = np.multiply(x,y)
new_arr1

array([[ 5, 12],
       [21, 32]])

In [94]:
# .sum()

np.sum(x)

10

In [95]:
# .prod

np.prod(x)

24

In [97]:
# random.rand(m,n) : generates random numbers between 0 ,1 
# m = rows, n= columns
np.random.rand(2,4)

array([[0.96008906, 0.96932429, 0.32256395, 0.72013635],
       [0.38990795, 0.75907897, 0.8849089 , 0.03862497]])

In [98]:
# random.randn(m,n) : generates random numbers between 0 ,1 
# m = rows, n= columns
np.random.randn(2,4)

array([[-0.41435843,  1.43313771,  0.67521495, -1.57329584],
       [-0.9125022 , -0.22732147,  1.31561909, -0.57933278]])

In [99]:
# generate intergers between some range
# np.random.randint(a,b,c) : a= min, b= max, c = number of elements 
np.random.randint(3,7,5)

array([3, 6, 4, 5, 3])

In [100]:
# zeros( ) : generates array of zeros 
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [101]:
# once  : generates array of ones

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [102]:
# ceil() : return ceil value of element

arr = np.array([1.1,2.3,3.7,4.8,5.0,6.1,4.9])
np.ceil(arr)

array([2., 3., 4., 5., 5., 7., 5.])

In [103]:
# floor() : return ceil value of element

arr = np.array([1.1,2.3,3.7,4.8,5.0,6.1,4.9])
np.floor(arr)

array([1., 2., 3., 4., 5., 6., 4.])

In [104]:
# ravel() : convert multi-dimentional array to single dimentional


In [105]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
np.ravel(b)

array([1, 2, 3, 4, 5, 6])

In [110]:
# sort : sorting elements present in an array

np.sort(d_arr)

array([135, 170, 180, 191, 250])

In [111]:
input_arr = np.array([1,2,3,4,5,6,4,3,6,2,4,6,8,1,4,6])
x = np.unique(input_arr)
x

array([1, 2, 3, 4, 5, 6, 8])

In [127]:
input_arr.shape

(16,)

In [112]:
# trigo

In [114]:
np.sin(np.pi/2)


1.0

In [115]:
np.cos(np.pi/2)

6.123233995736766e-17

In [118]:
# concatenation

In [120]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

a12 = np.concatenate((a1,a2))

In [121]:
a12

array([1, 2, 3, 4, 5, 6])

In [122]:
# stacking

In [123]:
np.stack((a1,a2),axis = 0)

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
np.hstack((a1,a2))

array([1, 2, 3, 4, 5, 6])

In [124]:
np.stack((a1,a2),axis = 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [126]:
np.vstack((a1,a2))

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
# reshape(row,col)

input_arr = np.array([1,2,3,4,5,6,4,3,6,2,4,6,8,1,4,6])

In [129]:
input_arr.shape

(16,)

In [130]:
input_arr.ndim

1

In [131]:
# 1*16
# 2*8
# 4*4
# 8*2
# 16*1

In [133]:
new_arr = input_arr.reshape(4,4)
new_arr

array([[1, 2, 3, 4],
       [5, 6, 4, 3],
       [6, 2, 4, 6],
       [8, 1, 4, 6]])

In [134]:
new_arr.ndim

2

In [135]:
new_arr.reshape(8,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [4, 3],
       [6, 2],
       [4, 6],
       [8, 1],
       [4, 6]])

In [136]:
# split

In [137]:
split_arr = np.split(input_arr,2)
split_arr

[array([1, 2, 3, 4, 5, 6, 4, 3]), array([6, 2, 4, 6, 8, 1, 4, 6])]

In [139]:
split_arr1 = np.split(input_arr,4)
split_arr1

[array([1, 2, 3, 4]),
 array([5, 6, 4, 3]),
 array([6, 2, 4, 6]),
 array([8, 1, 4, 6])]

In [140]:
# search in an array

In [141]:
m = np.array([1,2,3,4])
s1 = np.where(m==3)
s1

(array([2]),)

In [142]:
# search in  2D array

In [144]:
new_arr

array([[1, 2, 3, 4],
       [5, 6, 4, 3],
       [6, 2, 4, 6],
       [8, 1, 4, 6]])

In [145]:
np.where(new_arr==6)  # return index of all 6's

(array([1, 2, 2, 3]), array([1, 0, 3, 3]))

In [146]:
# filteration

d_arr

array([180, 170, 135, 191, 250])

In [147]:
d_arr>200

array([False, False, False, False,  True])

In [148]:
d_arr[d_arr>200]

array([250])

In [149]:
new_arr.T

array([[1, 5, 6, 8],
       [2, 6, 2, 1],
       [3, 4, 4, 4],
       [4, 3, 6, 6]])

In [150]:
# multiple conditions

In [154]:
d_arr[np.where((d_arr>150) & (d_arr<250))]

array([180, 170, 191])

In [155]:
d_arr[np.where((d_arr>150) | (d_arr<250))]

array([180, 170, 135, 191, 250])